import type { Metadata } from "next";
import { Suspense } from "react";
import SessionWrapper from "@/components/SessionWrapper";
import GlobalLoader from "@/components/GlobalLoader";
import { ThemeProvider } from "@/components/ThemeProvider";

import "./globals.css";
import "@/styles/custom.css";
import "@/styles/post-tags.css";

import "@/../public/assets/libs/tinymce/skins/ui/oxide/content.min.css";

import "@/styles/prism.js/prism-tomorrow-night.css";
import "@/styles/prism.js/prism-line-numbers.min.css";
import "highlight.js/styles/default.css";
import "@/../public/assets/libs/prism.js/prism-tomorrow-night.js";
import "@/../public/assets/libs/prism.js/prism-line-numbers.min.js";
import Navbar from "@/components/Navbar";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { Cormorant, IBM_Plex_Mono, Source_Sans_3 } from "next/font/google";
import { cn } from "@/lib/utils";

const fontDisplay = Cormorant({ subsets: ["latin"], weight: ["500", "600", "700"], variable: "--font-display" });
const fontBody = Source_Sans_3({ subsets: ["latin"], variable: "--font-body" });
const fontMono = IBM_Plex_Mono({ subsets: ["latin"], weight: ["400", "500"], variable: "--font-mono" });


config.autoAddCss = false;

export const metadata: Metadata = {
    title: "Vedev Blog",
    description: "Generated by vedev.guru",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <SessionWrapper>
            <html
                lang="en"
                className={cn("font-sans", fontDisplay.variable, fontBody.variable, fontMono.variable)}
                suppressHydrationWarning
            >
                <head>
                    <link
                        rel="stylesheet"
                        href="/assets/libs/tinymce/skins/ui/oxide/content.min.css"
                    />
                    <script
                        src="/assets/libs/tinymce/tinymce.min.js"
                        defer
                    ></script>
                    <script
                        src="/assets/libs/prism.js/prism-tomorrow-night.js"
                        defer
                    ></script>
                    <script
                        src="/assets/libs/prism.js/prism-line-numbers.min.js"
                        defer
                    ></script>
                </head>
                <body>
                    <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                        <Suspense fallback={null}>
                            <GlobalLoader />
                        </Suspense>
                        <Navbar />
                        {children}
                    </ThemeProvider>
                </body>
            </html>
        </SessionWrapper>
    );
}
