import type { Metadata } from "next";
import { Suspense } from "react";
import SessionWrapper from "@/components/SessionWrapper";
import GlobalLoader from "@/components/GlobalLoader";
import { ThemeProvider } from "@/components/ThemeProvider";

import "./globals.css";
import "@/styles/custom.css";

import Navbar from "@/components/Navbar";
import EmberField from "@/components/layout/EmberField";
import { Toaster } from "@/components/ui/sonner";

import { Newsreader, IBM_Plex_Mono, Literata } from "next/font/google";
import { cn } from "@/lib/utils";

const fontDisplay = Newsreader({ subsets: ["latin"], variable: "--font-display" });
const fontBody = Literata({ subsets: ["latin"], variable: "--font-body" });
const fontMono = IBM_Plex_Mono({ subsets: ["latin"], weight: ["400", "500"], variable: "--font-mono" });

export const metadata: Metadata = {
    title: "Vedev Blog",
    description: "Generated by vedev.guru",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <SessionWrapper>
            <html
                lang="en"
                className={cn("font-sans", fontDisplay.variable, fontBody.variable, fontMono.variable)}
                suppressHydrationWarning
            >
                <body>
                    <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                        <EmberField />
                        <Suspense fallback={null}>
                            <GlobalLoader />
                        </Suspense>
                        <Navbar />
                        {children}
                        <Toaster />
                    </ThemeProvider>
                </body>
            </html>
        </SessionWrapper>
    );
}
