import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import SessionWrapper from "@/components/SessionWrapper";
import GlobalLoader from "@/components/GlobalLoader";

import "@fontsource/roboto/400.css";
// import '@/styles/globals.css'
import "@/styles/custom.css";
import "@/styles/post-tags.css";

import "@/../public/assets/libs/tinymce/skins/ui/oxide/content.min.css";

import "@/styles/prism.js/prism-tomorrow-night.css";
import "@/styles/prism.js/prism-line-numbers.min.css";
import "highlight.js/styles/default.css";
import "@/../public/assets/libs/prism.js/prism-tomorrow-night.js";
import "@/../public/assets/libs/prism.js/prism-line-numbers.min.js";
import Navbar from "@/components/Navbar";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

export const metadata: Metadata = {
    title: "Vedev Blog",
    description: "Generated by vedev.guru",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <SessionWrapper>
            <html lang="en">
                <head>
                    <link
                        rel="stylesheet"
                        href="/assets/libs/tinymce/skins/ui/oxide/content.min.css"
                    />
                    <script
                        src="/assets/libs/tinymce/tinymce.min.js"
                        defer
                    ></script>
                    <script
                        src="/assets/libs/prism.js/prism-tomorrow-night.js"
                        defer
                    ></script>
                    <script
                        src="/assets/libs/prism.js/prism-line-numbers.min.js"
                        defer
                    ></script>
                </head>
                <body>
                    <AntdRegistry>
                        <GlobalLoader />
                        <Navbar />
                        {children}
                    </AntdRegistry>
                </body>
            </html>
        </SessionWrapper>
    );
}
